openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger MyApp
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /about:
    get:
      summary: Info about app
      operationId: aboutApp
      tags:
        - App
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/App"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    App:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        url:
          type: string
        port:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string